disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Shainil P S"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/profile.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "I'm Shainil P S, a software developer. I build backend and blockchain systems, tinker with low-level software, and spend way too much time in the terminal."
  copyright = "@2025 Shainil P S"

[params.author]
  name = "Shainil P S"
  email = "me@shainilps.com"
  image = "img/profile.jpeg"
  imageQuality = 96
  headline = "I'm a dev"
  bio = "I use neovim btw!!"
  about = "I mostly work with backend and blockchain technologies, building systems around them. Lately, Iâ€™ve been diving into low-level stuff as well. I primarily use [neovim](https://github.com/neovim/neovim) and [niri](https://github.com/YaLTeR/niri) for coding. If you want to connect, feel free to reach out!"
  links = [
    { email = "mailto:me@shainilps.com" },
    { github = "https://github.com/shainilps" },
    { x-twitter = "https://twitter.com/shainilps" },
    { linkedin = "https://linkedin.com/in/shainilps" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
